name: jonmoss
favicon: null
layout_spectrum: 0.6217287248000503
typography_spectrum: 0.6964598519261926
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2891087883617729
  lightness: 0.8138362041208893
  saturation: 0.3896312883589417
  rhythmicContrast: 0.0349941358435899
purpose: []
