typography_spectrum: 0.6964598519261926
color:
  saturation: 0.7222222
  brandStrength: 0.4014337
  lightness: 0.2562724
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  rhythmicContrast: 0.7240143
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.734767
analytics:
  twitter: null
  google: null
  facebook: null
author:
  name: Jonathan Moss
  email: art@jonmoss.org.uk
name: Jonathan Moss
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Sketchwork
    id: 14740c24-f3cc-4322-9725-85a7d868f84d
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Eat. Sleep. Sketch.
purpose: []
